<h1> importing libraries <h1/>

In [ ]:
# importing libraies
import numpy as np
import pandas as pd
import joblib

In [8]:
# importing sk learn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

print("sklearn imported")

sklearn imported

<h1>Load datasets<h1/>

In [10]:
df = pd.read_csv("boston_house_prices.csv")
print("loaded sucessfully")

loaded sucessfully

In [12]:
df.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [14]:
#inspections
print("\nDataset Info:")
df.info()

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    int64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64
 9   TAX      506 non-null    int64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB

In [16]:
print("\nDescriptive Statistics:")
df.describe()

Descriptive Statistics:

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [18]:
print("\n missing values: ")
df.isnull().sum()

 missing values:

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
MEDV       0
dtype: int64

In [21]:
print(df.isnull().sum().sum())

0

<h1> seperate features to independent(x) and dependent(y) <h1/>

In [42]:
# X = df.drop("MEDV" , axis=1)
x = df.drop("CHAS" , axis=1)
y = df["MEDV"]

In [44]:
x.head()

,CRIM,ZN,INDUS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [48]:
X = x.iloc[:,:-1]
X

,CRIM,ZN,INDUS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67
502,0.04527,0.0,11.93,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08
503,0.06076,0.0,11.93,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64
504,0.10959,0.0,11.93,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48
505,0.04741,0.0,11.93,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88

<h1> split dataset into traing and teating <h1/>

In [62]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(f"trainning set shape : {X_train.shape}")
print(f" testing set shape : {X_test.shape}")

trainning set shape : (404, 12)
 testing set shape : (102, 12)

<h1>applyy the feature transformation <h1/>

In [64]:
scalar = StandardScaler()

In [65]:
# fit the scalar on the training data and transform it
X_train_scaled = scalar.fit_transform(X_train)

In [69]:
X_test_scaled = scalar.transform(X_test)
print(X_test_scaled)

[[-0.39680933 -0.50032012 -1.00711147 ... -0.77195078  0.42887165
  -0.48121032]
 [-0.40079621  1.2294987  -0.66439105 ... -0.32270256  0.44418004
  -1.25709448]
 [-0.39523443 -0.50032012  2.43316256 ...  0.80041799  0.36993437
   0.79033849]
 ...
 [ 1.1779666  -0.50032012  1.03323679 ...  0.84534281 -3.5124912
   1.23390203]
 [-0.40131065 -0.50032012 -0.94321444 ...  0.08162084  0.43422959
   0.05669848]
 [-0.39643252 -0.50032012  0.26792466 ...  0.17147048  0.29470458
  -0.49529171]]

In [71]:
#initialising the linear regession model
model =LinearRegression()
model

LinearRegression()

In [73]:
#Training the model
model.fit(X_train_scaled, y_train)
print("model training complete")

model training complete

In [77]:
model.intercept_

np.float64(22.796534653465343)

In [78]:
model.coef_

array([-1.05650611,  0.73912906,  0.4171    , -1.90433945,  3.18770821,
       -0.14292628, -3.11463855,  2.45010906, -1.98077973, -2.10274882,
        1.1821675 , -3.72668025])

In [81]:
prediction = model.predict(X_test_scaled)
prediction

array([29.21866014, 33.5514672 , 14.81065799, 25.08472546, 19.17392702,
       23.28640399, 17.7441225 , 14.46092123, 23.30259107, 20.75647992,
       22.45317074, 18.77736488, -6.52970935, 21.74968493, 19.30195869,
       26.59522081, 21.21754878,  5.84256345, 40.88127145, 17.98690048,
       27.43177299, 30.29871753, 11.20759373, 24.39691543, 18.24007254,
       16.01087618, 22.79683608, 14.7395835 , 19.75576272, 19.29298669,
       22.52017326, 25.37983983, 26.36505651, 18.2369769 , 16.93419024,
       17.55836756, 31.50335902, 20.24159576, 21.08251444, 24.65267564,
       13.90452083, 32.57892685, 43.16818646, 17.12896113, 27.36706026,
       17.35854092, 14.01099631, 25.95229584, 20.56538298, 30.1790087 ,
       21.49771119, 34.68242963, 16.02334401, 26.33533751, 40.12023825,
       22.90083215, 19.30066018, 32.99670513, 25.11269667, 12.73224637,
       22.79239332, 30.71175958, 31.81487172, 15.82826036, 20.05819836,
       13.90910292, 20.92057234, 26.01802251, 30.8047209 , 11.73369775,
       20.50842276, 27.85098594, 11.20111241, 15.49838312, 23.81749186,
        6.14293872, 21.62836904, 41.88626638, 19.04288451,  8.71754251,
       20.7149105 , 13.32176762, 20.65818567,  9.52638634, 23.44962479,
       29.40116944, 19.46566931, 25.67438034, 29.40908719, 20.44020289,
       25.70799403,  5.59199842, 20.41059108, 14.70093463, 12.90622241,
       21.06007823, 25.17368387, -0.52045268, 13.85769946, 16.19518173,
       22.24816901, 24.52416597])

In [86]:
mse = mean_squared_error(y_test, prediction)
r2 = r2_score(y_test, prediction)

In [87]:
print(f" model performance on test set: ")
print(f" mean squared error(MSE): {mse:.2f}")
print(f"R-squared(R2): {r2:.2f}")

 model performance on test set:
 mean squared error(MSE): 24.64
R-squared(R2): 0.66

<h1> save the model and the scalars<h2/>